# Set the minimum iOS deployment target
platform :ios, '16.0'

# Prepare the React Native project
require_relative '../node_modules/react-native/scripts/react_native_pods'

# Flipper configuration (disabled for non-Flipper builds)
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

# If you're using frameworks, specify linkage type
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Super_select' do
  config = use_native_modules!

  # Firebase, Reanimated, and other necessary pods
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  
  $RNFirebaseAsStaticFramework = true

  # React Native dependencies
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'Super_selectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Post-installation hook
  post_install do |installer|
    react_native_post_install(installer)

    # Ensure the correct platform and configuration for your project
    installer.pods_project.targets.each do |target|
      if target.name == 'React-Core'
        target.build_configurations.each do |config|
          config.build_settings['EXCLUDED_ARCHITECTURES'] = 'arm64'  # Exclude arm64 architecture for M1 Macs on simulators
        end
      end
    end
  end
end
